// <auto-generated />
using BeerApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerApi.Migrations
{
    [DbContext(typeof(BeerApiContext))]
    [Migration("20220329211501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BeerApi.Models.Beer", b =>
                {
                    b.Property<int>("BeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abv")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Brewery")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Style")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BeerId");

                    b.ToTable("Beers");
                });
#pragma warning restore 612, 618
        }
    }
}
